### ISSUE TITLE
using in Jetson Nano

### ISSUE THREAD

**Issue by SJavad** [adafruit/Adafruit_BME280_Library#108]
can I use this Library on Jetson Nano to integrate with the sensor ? 
I have Jetson nano that have I2C pins and want to connect to the sensor and read temperature and pressure value.
how can I do that ?

**Comment by SJavad** [comment]
@adafruit 
I am still waiting for an answer...
I don't want to use Arduino
I am using Jetson and I Recognize the bme280 on the i2c bus by entering the `sudo i2cdetect -r -y 1` command.
can I use this library for connecting and reading temperature and pressure values?

**Comment by dhalbert** [comment]
This is a C++ Arduino library, meant to run on microcontrollers that support Arduino. Instead of using Arduino, you can use Python. In particular, you can use the Blinka library, which runs on top of "regular" Python and emulates CircuitPython features. Then you can use CircuitPython libraries, in this case, https://github.com/adafruit/Adafruit_CircuitPython_BME280.

See https://learn.adafruit.com/circuitpython-libraries-on-linux-and-the-nvidia-jetson-nano for a guide on how to set up and use Blinka.

I'm going to close this issue. If you would like further support on this, see our discord, https://adafru.it/discord and the #help-with-linux-sbcs channel, or you can post in our forums https://forums.adafruit.com.
